Repository corekit-ui/corekit-ui, pull requests merged in 2025-02, with the labels that each got.

#22 feat(components): dialog
  eslint.config.js
  projects/docs/src/app/app.component.html
  projects/docs/src/app/app.component.ts
  projects/docs/src/app/features/components/dialog-page/dialog-page.component.html
  projects/docs/src/app/features/components/dialog-page/dialog-page.component.ts
  projects/docs/src/styles.css
  projects/ui/autocomplete/autocomplete.ts
  projects/ui/card/card.ts
  projects/ui/close/closable.ts
  projects/ui/close/close.html
  projects/ui/close/close.styles.ts
  projects/ui/close/close.ts
  projects/ui/close/index.ts
  projects/ui/close/ng-package.json
  projects/ui/close/package.json
  projects/ui/close/public-api.ts
  projects/ui/dialog/body/dialog-actions.styles.ts
  projects/ui/dialog/body/dialog-actions.ts
  projects/ui/dialog/body/dialog-content.ts
  projects/ui/dialog/body/dialog-header.html
  projects/ui/dialog/body/dialog-header.styles.ts
  projects/ui/dialog/body/dialog-header.ts
  projects/ui/dialog/body/dialog-subtitle.ts
  projects/ui/dialog/body/dialog-title.ts
  projects/ui/dialog/dialog-config.ts
  projects/ui/dialog/dialog-container.styles.ts
  projects/ui/dialog/dialog-container.ts
  projects/ui/dialog/dialog-ref.ts
  projects/ui/dialog/dialog.tokens.ts
  projects/ui/dialog/dialog.ts
  projects/ui/dialog/index.ts
  projects/ui/dialog/ng-package.json
  projects/ui/dialog/package.json
  projects/ui/dialog/public-api.ts
  projects/ui/dialog/zoom-in.animation.ts
  projects/ui/form-field/form-field.ts
  projects/ui/reactive-forms/error-state-matcher.ts
Labels: feature

#23 fix(components/dialog): illegal imports
  projects/ui/dialog/dialog.ts
Labels: bug

#24 refactor(styles): more consistent outline
  projects/docs/src/app/features/components/autocomplete-page/autocomplete-page.component.html
  projects/docs/src/styles.css
  projects/docs/tailwind.config.ts
  projects/ui/accordion/components/accordion-item-header/accordion-item-header.ts
  projects/ui/button/button.styles.ts
  projects/ui/checkbox/checkbox.styles.ts
  projects/ui/close/close.styles.ts
  projects/ui/dialog/dialog-container.ts
  projects/ui/input/input.styles.ts
  projects/ui/label/label.ts
  projects/ui/option/option.styles.ts
  projects/ui/radio/radio.styles.ts
Labels: enhancement, P1

#33 fix(components/autocomplete): options rendered incorrectly after the the existing value is cleared
  projects/ui/autocomplete/autocomplete-trigger.ts
  projects/ui/autocomplete/autocomplete.ts
Labels: bug, P0

#35 refactor(components/typography): more intuitive API
  projects/docs/src/app/app.component.html
  projects/docs/src/app/app.component.ts
  projects/docs/src/app/features/components/accordion-page/accordion-page.component.html
  projects/docs/src/app/features/components/accordion-page/accordion-page.component.ts
  projects/docs/src/app/features/components/autocomplete-page/autocomplete-page.component.html
  projects/docs/src/app/features/components/autocomplete-page/autocomplete-page.component.ts
  projects/docs/src/app/features/components/avatar-page/avatar-page.component.html
  projects/docs/src/app/features/components/button-page/button-page.component.html
  projects/docs/src/app/features/components/button-page/button-page.component.ts
  projects/docs/src/app/features/components/card-page/card-page.component.ts
  projects/docs/src/app/features/components/dialog-page/dialog-page.component.ts
  projects/docs/src/app/features/components/form-field-page/form-field-page.component.html
  projects/docs/src/app/features/components/form-field-page/form-field-page.component.ts
  projects/docs/src/app/features/components/typography-page/typography-page.component.html
  projects/docs/src/app/features/components/typography-page/typography-page.component.ts
  projects/docs/src/index.html
  projects/docs/src/styles.css
  projects/ui/accordion/components/accordion-item/accordion-item.html
  projects/ui/alert/directives/alert-body.ts
  projects/ui/avatar/avatar.styles.ts
  projects/ui/button/button.styles.ts
  projects/ui/card/card-content.ts
  projects/ui/card/card-subtitle.ts
  projects/ui/card/card.ts
  projects/ui/common/class-names.pipe.ts
  projects/ui/common/index.ts
  projects/ui/common/ng-package.json
  projects/ui/common/package.json
  projects/ui/common/public-api.ts
  projects/ui/dialog/dialog-container.styles.ts
  projects/ui/input/input.styles.ts
  projects/ui/label/label.ts
  projects/ui/package.json
  projects/ui/styles/default-theme.css
  projects/ui/styles/index.css
  projects/ui/styles/reset.css
  projects/ui/styles/typography.css
  projects/ui/typography/blockquote.ts
  projects/ui/typography/code.ts
  projects/ui/typography/display.ts
  projects/ui/typography/h1.ts
  projects/ui/typography/h2.ts
  projects/ui/typography/h3.ts
  projects/ui/typography/h4.ts
  projects/ui/typography/index.ts
  projects/ui/typography/lead.ts
  projects/ui/typography/list.ts
  projects/ui/typography/ng-package.json
  projects/ui/typography/ol.ts
  projects/ui/typography/p.ts
  projects/ui/typography/package.json
  projects/ui/typography/public-api.ts
  projects/ui/typography/small.ts
  projects/ui/typography/ul.ts
Labels: enhancement, P0

#37 refactor(components): increase form elements touch area on mobile devices
  projects/docs/src/app/features/components/autocomplete-page/autocomplete-page.component.html
  projects/docs/src/app/features/components/card-page/card-page.component.html
  projects/docs/src/app/features/components/form-field-page/form-field-page.component.html
  projects/docs/src/app/features/components/input-page/input-page.component.html
  projects/ui/button/button.styles.ts
  projects/ui/checkbox/checkbox.styles.ts
  projects/ui/checkbox/checkbox.ts
  projects/ui/form-field/directives/error.ts
  projects/ui/form-field/form-field.ts
  projects/ui/input/input-prefix.ts
  projects/ui/input/input-suffix.ts
  projects/ui/input/input.styles.ts
  projects/ui/label/label.ts
  projects/ui/radio/radio.styles.ts
  projects/ui/styles/index.css
Labels: enhancement, P0

#29 feat(table): component implementation
  eslint.config.js
  projects/docs/src/app/app.component.html
  projects/docs/src/app/app.component.ts
  projects/docs/src/app/features/components/table-page/table-page.component.html
  projects/docs/src/app/features/components/table-page/table-page.component.ts
  projects/ui/table/cell-def.ts
  projects/ui/table/cell.ts
  projects/ui/table/column-def.ts
  projects/ui/table/index.ts
  projects/ui/table/ng-package.json
  projects/ui/table/package.json
  projects/ui/table/public-api.ts
  projects/ui/table/row-def.ts
  projects/ui/table/row.ts
  projects/ui/table/table.html
  projects/ui/table/table.ts
Labels: feature, P0

#40 fix(components/table): not calling computed signal in class bindings
  projects/ui/table/cell.ts
  projects/ui/table/row.ts
Labels: bug
